name: Run docker

on:
  workflow_dispatch:
  
env:
  DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
  DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}

jobs:
  run_web:
    runs-on: ubuntu-20.04
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
    - name: Destroy Docker image
      run: |
        docker login -u ${DOCKER_USERNAME} -p ${DOCKER_PASSWORD}
        docker images
        docker rmi okteto
